enum SkPixelGeometry {
    "kUnknown_SkPixelGeometry",
    "kRGB_H_SkPixelGeometry",
    "kBGR_H_SkPixelGeometry",
    "kRGB_V_SkPixelGeometry",
    "kBGR_V_SkPixelGeometry"
};

enum SkSurfaceProps_Flags {
    "SkSurfaceProps::kUseDeviceIndependentFonts_Flag"
};

enum SkSurfaceProps_InitType {
    "SkSurfaceProps::kLegacyFontHost_InitType"
};

interface SkSurfaceProps {
    void SkSurfaceProps(long flags, SkPixelGeometry geo);
    void SkSurfaceProps(SkSurfaceProps_InitType initType);
    void SkSurfaceProps(long flags, SkSurfaceProps_InitType initType);
    void SkSurfaceProps([Const, Ref]SkSurfaceProps other)

    [Const] long flags();
    [Const] SkPixelGeometry pixelGeometry();
    [Const] boolean isUseDeviceIndependentFonts();

    [Operator="==", Const] boolean equals([Const, Ref] SkSurfaceProps that);
};
